//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SQLResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DEL_USERS.
        /// </summary>
        internal static string USP_DEL_USERS {
            get {
                return ResourceManager.GetString("USP_DEL_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GET_USERS_LOGIN.
        /// </summary>
        internal static string USP_GET_USERS_LOGIN {
            get {
                return ResourceManager.GetString("USP_GET_USERS_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GET_USERS_PERMISSION.
        /// </summary>
        internal static string USP_GET_USERS_PERMISSION {
            get {
                return ResourceManager.GetString("USP_GET_USERS_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_INS_USERS.
        /// </summary>
        internal static string USP_INS_USERS {
            get {
                return ResourceManager.GetString("USP_INS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UPD_USERS.
        /// </summary>
        internal static string USP_UPD_USERS {
            get {
                return ResourceManager.GetString("USP_UPD_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UPD_USERS_CHANGE_PWD.
        /// </summary>
        internal static string USP_UPD_USERS_CHANGE_PWD {
            get {
                return ResourceManager.GetString("USP_UPD_USERS_CHANGE_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UPD_USERS_LOCK.
        /// </summary>
        internal static string USP_UPD_USERS_LOCK {
            get {
                return ResourceManager.GetString("USP_UPD_USERS_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UPD_USERS_LOGOUT.
        /// </summary>
        internal static string USP_UPD_USERS_LOGOUT {
            get {
                return ResourceManager.GetString("USP_UPD_USERS_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM V_ROLES.
        /// </summary>
        internal static string VIEW_ROLES {
            get {
                return ResourceManager.GetString("VIEW_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM V_USERS.
        /// </summary>
        internal static string VIEW_USERS {
            get {
                return ResourceManager.GetString("VIEW_USERS", resourceCulture);
            }
        }
    }
}
