//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SQLResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM APPRAISAL_ASSETS_DETAIL WHERE APPRAISAL_ASSETS_ID = :AppraisalID AND STATUS = 1.
        /// </summary>
        internal static string GET_APPRAISAL_DETAIL_BY_ID {
            get {
                return ResourceManager.GetString("GET_APPRAISAL_DETAIL_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM APPRAISAL_ASSETS_JOB WHERE APPRAISAL_ASSETS_ID = :AppraisalID AND STATUS = 1.
        /// </summary>
        internal static string GET_APPRAISAL_JOB_BY_ID {
            get {
                return ResourceManager.GetString("GET_APPRAISAL_JOB_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM COMPARE_ASSETS WHERE APPRAISAL_ASSETS_ID = :AppraisalID AND STATUS = 1.
        /// </summary>
        internal static string GET_COMPARE_BY_ID {
            get {
                return ResourceManager.GetString("GET_COMPARE_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM IMAGE_ASSETS WHERE APPRAISAL_ASSETS_ID = :AppraisalID AND UPLOAD_TYPE_ID = :UploadTypeID AND STATUS = 1.
        /// </summary>
        internal static string GET_IMAGE_ASSETS_BY_ID {
            get {
                return ResourceManager.GetString("GET_IMAGE_ASSETS_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM LOCATION_ASSETS WHERE APPRAISAL_ASSETS_ID = :AppraisalID AND STATUS = 1.
        /// </summary>
        internal static string GET_LOCATION_ASSETS_BY_ID {
            get {
                return ResourceManager.GetString("GET_LOCATION_ASSETS_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM MAP_ASSETS WHERE APPRAISAL_ASSETS_ID = :AppraisalID AND STATUS = 1.
        /// </summary>
        internal static string GET_MAP_ASSETS_BY_ID {
            get {
                return ResourceManager.GetString("GET_MAP_ASSETS_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DEL_APPRAISAL_DETAIL.
        /// </summary>
        internal static string USP_DEL_APPRAISAL_DETAIL {
            get {
                return ResourceManager.GetString("USP_DEL_APPRAISAL_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DEL_APPRAISAL_JOB.
        /// </summary>
        internal static string USP_DEL_APPRAISAL_JOB {
            get {
                return ResourceManager.GetString("USP_DEL_APPRAISAL_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DEL_COMPARE_ASSET.
        /// </summary>
        internal static string USP_DEL_COMPARE_ASSET {
            get {
                return ResourceManager.GetString("USP_DEL_COMPARE_ASSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DEL_LOCATION_ASSET.
        /// </summary>
        internal static string USP_DEL_LOCATION_ASSET {
            get {
                return ResourceManager.GetString("USP_DEL_LOCATION_ASSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DEL_MAP.
        /// </summary>
        internal static string USP_DEL_MAP {
            get {
                return ResourceManager.GetString("USP_DEL_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DEL_UPLOAD_PICTURE.
        /// </summary>
        internal static string USP_DEL_UPLOAD_PICTURE {
            get {
                return ResourceManager.GetString("USP_DEL_UPLOAD_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DEL_USERS.
        /// </summary>
        internal static string USP_DEL_USERS {
            get {
                return ResourceManager.GetString("USP_DEL_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GET_USERS_LOGIN.
        /// </summary>
        internal static string USP_GET_USERS_LOGIN {
            get {
                return ResourceManager.GetString("USP_GET_USERS_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_GET_USERS_PERMISSION.
        /// </summary>
        internal static string USP_GET_USERS_PERMISSION {
            get {
                return ResourceManager.GetString("USP_GET_USERS_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_INS_UPLOAD_PICTURE.
        /// </summary>
        internal static string USP_INS_UPLOAD_PICTURE {
            get {
                return ResourceManager.GetString("USP_INS_UPLOAD_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_INS_USERS.
        /// </summary>
        internal static string USP_INS_USERS {
            get {
                return ResourceManager.GetString("USP_INS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_MNG_APPRAISAL_DETAIL.
        /// </summary>
        internal static string USP_MNG_APPRAISAL_DETAIL {
            get {
                return ResourceManager.GetString("USP_MNG_APPRAISAL_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_MNG_APPRAISAL_JOB.
        /// </summary>
        internal static string USP_MNG_APPRAISAL_JOB {
            get {
                return ResourceManager.GetString("USP_MNG_APPRAISAL_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_MNG_COMPARE_ASSET.
        /// </summary>
        internal static string USP_MNG_COMPARE_ASSET {
            get {
                return ResourceManager.GetString("USP_MNG_COMPARE_ASSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_MNG_LOCATION_ASSET.
        /// </summary>
        internal static string USP_MNG_LOCATION_ASSET {
            get {
                return ResourceManager.GetString("USP_MNG_LOCATION_ASSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_MNG_MAP.
        /// </summary>
        internal static string USP_MNG_MAP {
            get {
                return ResourceManager.GetString("USP_MNG_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UPD_USERS.
        /// </summary>
        internal static string USP_UPD_USERS {
            get {
                return ResourceManager.GetString("USP_UPD_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UPD_USERS_CHANGE_PWD.
        /// </summary>
        internal static string USP_UPD_USERS_CHANGE_PWD {
            get {
                return ResourceManager.GetString("USP_UPD_USERS_CHANGE_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UPD_USERS_LOCK.
        /// </summary>
        internal static string USP_UPD_USERS_LOCK {
            get {
                return ResourceManager.GetString("USP_UPD_USERS_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UPD_USERS_LOGOUT.
        /// </summary>
        internal static string USP_UPD_USERS_LOGOUT {
            get {
                return ResourceManager.GetString("USP_UPD_USERS_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM V_AMPHUR.
        /// </summary>
        internal static string VIEW_AMPHUR {
            get {
                return ResourceManager.GetString("VIEW_AMPHUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM V_DISTRICT.
        /// </summary>
        internal static string VIEW_DISTRICT {
            get {
                return ResourceManager.GetString("VIEW_DISTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM V_FILTER.
        /// </summary>
        internal static string VIEW_FILTER {
            get {
                return ResourceManager.GetString("VIEW_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM V_PROVINCE.
        /// </summary>
        internal static string VIEW_PROVINCE {
            get {
                return ResourceManager.GetString("VIEW_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM V_ROLES.
        /// </summary>
        internal static string VIEW_ROLES {
            get {
                return ResourceManager.GetString("VIEW_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM V_USERS.
        /// </summary>
        internal static string VIEW_USERS {
            get {
                return ResourceManager.GetString("VIEW_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM V_APPRAISAL_LIST.
        /// </summary>
        internal static string V_APPRAISAL_LIST {
            get {
                return ResourceManager.GetString("V_APPRAISAL_LIST", resourceCulture);
            }
        }
    }
}
