DELIMITER $$

USE `appraisalasset`$$

DROP PROCEDURE IF EXISTS `USP_UPD_USERS_LOGOUT`$$

CREATE DEFINER=`sa`@`%` PROCEDURE `USP_UPD_USERS_LOGOUT`(
	IN iUser VARCHAR(50))
BEGIN
	UPDATE USERS
	SET USER_LOGIN = 0
	WHERE USER_NAME = iUser OR USER_ID = iUser AND DELETE_FLAG = 0;
    END$$

DELIMITER ;